shellEmulator: true

trustPolicy: no-downgrade

packages:
  - examples/*
  - docs/
catalog:
  '@types/react': ~19.2.10
  '@types/react-dom': ~19.2.3
  react: ^19.2.4
  react-dom: ^19.2.4
  vite: ^6.4.1
