/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as JsonImport } from './routes/json'
import { Route as DynamicImport } from './routes/dynamic'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DynamicParamImport } from './routes/dynamic/$param'

// Create/Update Routes

const JsonRoute = JsonImport.update({
  path: '/json',
  getParentRoute: () => rootRoute,
} as any)

const DynamicRoute = DynamicImport.update({
  path: '/dynamic',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DynamicParamRoute = DynamicParamImport.update({
  path: '/$param',
  getParentRoute: () => DynamicRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dynamic': {
      id: '/dynamic'
      path: '/dynamic'
      fullPath: '/dynamic'
      preLoaderRoute: typeof DynamicImport
      parentRoute: typeof rootRoute
    }
    '/json': {
      id: '/json'
      path: '/json'
      fullPath: '/json'
      preLoaderRoute: typeof JsonImport
      parentRoute: typeof rootRoute
    }
    '/dynamic/$param': {
      id: '/dynamic/$param'
      path: '/$param'
      fullPath: '/dynamic/$param'
      preLoaderRoute: typeof DynamicParamImport
      parentRoute: typeof DynamicImport
    }
  }
}

// Create and export the route tree

interface DynamicRouteChildren {
  DynamicParamRoute: typeof DynamicParamRoute
}

const DynamicRouteChildren: DynamicRouteChildren = {
  DynamicParamRoute: DynamicParamRoute,
}

const DynamicRouteWithChildren =
  DynamicRoute._addFileChildren(DynamicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dynamic': typeof DynamicRouteWithChildren
  '/json': typeof JsonRoute
  '/dynamic/$param': typeof DynamicParamRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dynamic': typeof DynamicRouteWithChildren
  '/json': typeof JsonRoute
  '/dynamic/$param': typeof DynamicParamRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dynamic': typeof DynamicRouteWithChildren
  '/json': typeof JsonRoute
  '/dynamic/$param': typeof DynamicParamRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/dynamic' | '/json' | '/dynamic/$param'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/dynamic' | '/json' | '/dynamic/$param'
  id: '__root__' | '/' | '/about' | '/dynamic' | '/json' | '/dynamic/$param'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DynamicRoute: typeof DynamicRouteWithChildren
  JsonRoute: typeof JsonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DynamicRoute: DynamicRouteWithChildren,
  JsonRoute: JsonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/dynamic",
        "/json"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dynamic": {
      "filePath": "dynamic.tsx",
      "children": [
        "/dynamic/$param"
      ]
    },
    "/json": {
      "filePath": "json.tsx"
    },
    "/dynamic/$param": {
      "filePath": "dynamic/$param.tsx",
      "parent": "/dynamic"
    }
  }
}
ROUTE_MANIFEST_END */
